[package]
name = "rbbench"
version = "0.1.0"
authors = ["Titus Tienaah <titus.intdxdt@gmail.com>"]

[dev-dependencies]
[dependencies]
rand = "0.3.15"
time = "*"
rbsegs = { git = "https://github.com/intdxdt/rbsegs", branch = "master" }
